services:
  eventsim:
    image: khoramism/event-generator-eventsim:1.2
    container_name: eventsim
    volumes:
      - ./config.json:/config.json
    command: >
      bin/eventsim -c "/config.json" --from 365 --nusers 30000 --growth-rate 0.30 /data/fake.json
    restart: unless-stopped
