global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'clickhouse'
    metrics_path: /metrics
    static_configs:
      - targets: ['clickhouse:8123']

  - job_name: 'metabase'
    metrics_path: /api/health
    static_configs:
      - targets: ['metabase:3001']

  - job_name: 'grafana'
    metrics_path: /api/health
    static_configs:
      - targets: ['grafana:3000']
