global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka:7071']
